-- skapa roll för ETL
CREATE ROLE IF NOT EXISTS ETL_DLT_ROLE;
CREATE ROLE IF NOT EXISTS TRANSFORM_DBT_ROLE;
CREATE ROLE IF NOT EXISTS BI_ROLE;

USE ROLE SECURITYADMIN;

--DLT ROLE

GRANT ROLE ETL_DLT_ROLE TO USER DLT_USER;
GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON DATABASE HR_ANALYTICS TO ROLE ETL_DLT_ROLE;

GRANT USAGE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE ETL_DLT_ROLE;
GRANT CREATE TABLE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE ETL_DLT_ROLE;

-- ge usage på övriga schemas (read access)
GRANT USAGE ON SCHEMA HR_ANALYTICS.WAREHOUSE TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON SCHEMA HR_ANALYTICS.MART TO ROLE ETL_DLT_ROLE;

--DBT ROLE

GRANT ROLE TRANSFORM_DBT_ROLE TO USER DBT_USER;
GRANT ROLE TRANSFORM_DBT_ROLE TO USER DBT_USER;

GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH TO ROLE TRANSFORM_DBT_ROLE;

GRANT USAGE ON DATABASE HR_ANALYTICS TO ROLE TRANSFORM_DBT_ROLE;

GRANT USAGE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE TRANSFORM_DBT_ROLE;

GRANT CREATE TABLE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE TRANSFORM_DBT_ROLE;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA HR_ANALYTICS.STAGING TO ROLE TRANSFORM_DBT_ROLE;

GRANT INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA HR_ANALYTICS.STAGING TO ROLE TRANSFORM_DBT_ROLE;

SHOW GRANTS ON SCHEMA HR_ANALYTICS.STAGING;

--BI ROLE
GRANT ROLE BI_ROLE TO USER BI_USER;

GRANT USAGE ON DATABASE HR_ANALYTICS TO ROLE BI_ROLE;

