USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS HR_ANALYTICS;
USE DATABASE HR_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS MART;

CREATE WAREHOUSE IF NOT EXISTS HR_ANALYTICS_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;


