-- skapa roll för ETL
CREATE ROLE IF NOT EXISTS ETL_DLT_ROLE;

-- ge rättigheter (minimala för att skriva till STAGING)
GRANT USAGE ON WAREHOUSE HR_ANALYTICS_WH TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON DATABASE HR_ANALYTICS TO ROLE ETL_DLT_ROLE;

GRANT USAGE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE ETL_DLT_ROLE;
GRANT CREATE TABLE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE ETL_DLT_ROLE;

-- ge usage på övriga schemas (read access)
GRANT USAGE ON SCHEMA HR_ANALYTICS.WAREHOUSE TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON SCHEMA HR_ANALYTICS.MART TO ROLE ETL_DLT_ROLE;
