-- skapa DB och schemas
CREATE DATABASE IF NOT EXISTS HR_ANALYTICS;
USE DATABASE HR_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS MART;

-- skapa ett warehouse (om du inte har ett)
CREATE WAREHOUSE IF NOT EXISTS YOUR_WAREHOUSE WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- skapa roll och användare för dlt
CREATE ROLE IF NOT EXISTS ETL_DLT_ROLE;
CREATE USER IF NOT EXISTS DLT_USER PASSWORD = 'PLACEHOLDER_PASSWORD' DEFAULT_ROLE = ETL_DLT_ROLE MUST_CHANGE_PASSWORD = FALSE;

-- ge rättigheter (minimala för att skriva till STAGING)
GRANT USAGE ON WAREHOUSE YOUR_WAREHOUSE TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON DATABASE HR_ANALYTICS TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE ETL_DLT_ROLE;
GRANT CREATE TABLE ON SCHEMA HR_ANALYTICS.STAGING TO ROLE ETL_DLT_ROLE;

-- ge läs/skriv för WAREHOUSE och MART (justera vid behov)
GRANT USAGE ON SCHEMA HR_ANALYTICS.WAREHOUSE TO ROLE ETL_DLT_ROLE;
GRANT USAGE ON SCHEMA HR_ANALYTICS.MART TO ROLE ETL_DLT_ROLE;

-- koppla rollen till user
GRANT ROLE ETL_DLT_ROLE TO USER DLT_USER;
