USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS DLT_USER
  PASSWORD = 'PLACEHOLDER_PASSWORD'
  DEFAULT_ROLE = ETL_DLT_ROLE
  DEFAULT_WAREHOUSE = HR_ANALYTICS_WH
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS DBT_USER
  PASSWORD = 'RANDOM_PASSWORD'
  DEFAULT_ROLE = TRANSFORM_DBT_ROLE
  DEFAULT_WAREHOUSE = HR_ANALYTICS_WH
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS BI_USER
  PASSWORD = 'BI_RANDO_PASS'
  DEFAULT_ROLE = BI_ROLE
  DEFAULT_WAREHOUSE = HR_ANALYTICS_WH
  MUST_CHANGE_PASSWORD = FALSE;