[destination.snowflake.credentials]
username = "DLT_USER"         # t.ex. DLT_USER
password = "PLACEHOLDER_PASSWORD"
account = "YOUR_ACCOUNT_LOCATOR"   # e.g. ab12345.eu-central-1
database = "HR_ANALYTICS"
warehouse = "YOUR_WAREHOUSE"
role = "ETL_DLT_ROLE"
